// Code generated by go-swagger; DO NOT EDIT.

package policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"my-swagger/src/pkg/v1/models"
)

// AddPolicyReader is a Reader for the AddPolicy structure.
type AddPolicyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddPolicyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAddPolicyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewAddPolicyInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAddPolicyOK creates a AddPolicyOK with default headers values
func NewAddPolicyOK() *AddPolicyOK {
	return &AddPolicyOK{}
}

/* AddPolicyOK describes a response with status code 200, with default header values.

Success
*/
type AddPolicyOK struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string
}

func (o *AddPolicyOK) Error() string {
	return fmt.Sprintf("[POST /policies][%d] addPolicyOK ", 200)
}

func (o *AddPolicyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	return nil
}

// NewAddPolicyInternalServerError creates a AddPolicyInternalServerError with default headers values
func NewAddPolicyInternalServerError() *AddPolicyInternalServerError {
	return &AddPolicyInternalServerError{}
}

/* AddPolicyInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type AddPolicyInternalServerError struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

func (o *AddPolicyInternalServerError) Error() string {
	return fmt.Sprintf("[POST /policies][%d] addPolicyInternalServerError  %+v", 500, o.Payload)
}
func (o *AddPolicyInternalServerError) GetPayload() *models.Errors {
	return o.Payload
}

func (o *AddPolicyInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
