// Code generated by go-swagger; DO NOT EDIT.

package policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"my-swagger/src/pkg/v1/models"
)

// NewAddPolicyParams creates a new AddPolicyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddPolicyParams() *AddPolicyParams {
	return &AddPolicyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddPolicyParamsWithTimeout creates a new AddPolicyParams object
// with the ability to set a timeout on a request.
func NewAddPolicyParamsWithTimeout(timeout time.Duration) *AddPolicyParams {
	return &AddPolicyParams{
		timeout: timeout,
	}
}

// NewAddPolicyParamsWithContext creates a new AddPolicyParams object
// with the ability to set a context for a request.
func NewAddPolicyParamsWithContext(ctx context.Context) *AddPolicyParams {
	return &AddPolicyParams{
		Context: ctx,
	}
}

// NewAddPolicyParamsWithHTTPClient creates a new AddPolicyParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddPolicyParamsWithHTTPClient(client *http.Client) *AddPolicyParams {
	return &AddPolicyParams{
		HTTPClient: client,
	}
}

/* AddPolicyParams contains all the parameters to send to the API endpoint
   for the add policy operation.

   Typically these are written to a http.Request.
*/
type AddPolicyParams struct {

	/* XRequestID.

	   An unique ID for the request
	*/
	XRequestID *string

	/* Policy.

	   The policy to create
	*/
	Policy *models.Policy

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add policy params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddPolicyParams) WithDefaults() *AddPolicyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add policy params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddPolicyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add policy params
func (o *AddPolicyParams) WithTimeout(timeout time.Duration) *AddPolicyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add policy params
func (o *AddPolicyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add policy params
func (o *AddPolicyParams) WithContext(ctx context.Context) *AddPolicyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add policy params
func (o *AddPolicyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add policy params
func (o *AddPolicyParams) WithHTTPClient(client *http.Client) *AddPolicyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add policy params
func (o *AddPolicyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXRequestID adds the xRequestID to the add policy params
func (o *AddPolicyParams) WithXRequestID(xRequestID *string) *AddPolicyParams {
	o.SetXRequestID(xRequestID)
	return o
}

// SetXRequestID adds the xRequestId to the add policy params
func (o *AddPolicyParams) SetXRequestID(xRequestID *string) {
	o.XRequestID = xRequestID
}

// WithPolicy adds the policy to the add policy params
func (o *AddPolicyParams) WithPolicy(policy *models.Policy) *AddPolicyParams {
	o.SetPolicy(policy)
	return o
}

// SetPolicy adds the policy to the add policy params
func (o *AddPolicyParams) SetPolicy(policy *models.Policy) {
	o.Policy = policy
}

// WriteToRequest writes these params to a swagger request
func (o *AddPolicyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XRequestID != nil {

		// header param X-Request-Id
		if err := r.SetHeaderParam("X-Request-Id", *o.XRequestID); err != nil {
			return err
		}
	}
	if o.Policy != nil {
		if err := r.SetBodyParam(o.Policy); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
