// Code generated by go-swagger; DO NOT EDIT.

// Package server CED API
//
//  These APIs provide services for manipulating Cloud Edge Distribution (aka CED) project.
//  Schemes:
//    http
//  Host: local.noip.site
//  BasePath: /api/ced/v1/
//  Version: 1.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package server
