// Code generated by go-swagger; DO NOT EDIT.

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "These APIs provide services for manipulating Cloud Edge Distribution (aka CED) project.",
    "title": "CED API",
    "version": "1.0"
  },
  "host": "local.noip.site",
  "basePath": "/api/ced/v1/",
  "paths": {
    "/policies": {
      "post": {
        "description": "Create policy",
        "tags": [
          "Policy"
        ],
        "summary": "Create policy",
        "operationId": "addPolicy",
        "parameters": [
          {
            "$ref": "#/parameters/requestId"
          },
          {
            "description": "The policy to create",
            "name": "policy",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Policy"
            }
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/responses/200"
          },
          "500": {
            "$ref": "#/responses/500"
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "description": "a model for all the error response coming from harbor",
      "type": "object",
      "properties": {
        "code": {
          "description": "The error code",
          "type": "string"
        },
        "message": {
          "description": "The error message",
          "type": "string"
        }
      }
    },
    "Errors": {
      "description": "The error array that describe the errors got during the handling of request",
      "type": "object",
      "properties": {
        "errors": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Error"
          }
        }
      }
    },
    "Policy": {
      "description": "The model for policy",
      "type": "object",
      "properties": {
        "id": {
          "description": "The policy id",
          "type": "integer"
        },
        "name": {
          "description": "The policy name",
          "type": "string"
        }
      }
    }
  },
  "parameters": {
    "id": {
      "minLength": 1,
      "type": "string",
      "description": "An unique ID for specific resource",
      "name": "id",
      "in": "path",
      "required": true
    },
    "requestId": {
      "minLength": 1,
      "type": "string",
      "description": "An unique ID for the request",
      "name": "X-Request-Id",
      "in": "header"
    }
  },
  "responses": {
    "200": {
      "description": "Success",
      "headers": {
        "X-Request-Id": {
          "type": "string",
          "description": "The ID of the corresponding request for the response"
        }
      }
    },
    "500": {
      "description": "Internal server error",
      "schema": {
        "$ref": "#/definitions/Errors"
      },
      "headers": {
        "X-Request-Id": {
          "type": "string",
          "description": "The ID of the corresponding request for the response"
        }
      }
    }
  },
  "securityDefinitions": {
    "basic": {
      "type": "basic"
    }
  },
  "security": [
    {
      "basic": []
    },
    {}
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "These APIs provide services for manipulating Cloud Edge Distribution (aka CED) project.",
    "title": "CED API",
    "version": "1.0"
  },
  "host": "local.noip.site",
  "basePath": "/api/ced/v1/",
  "paths": {
    "/policies": {
      "post": {
        "description": "Create policy",
        "tags": [
          "Policy"
        ],
        "summary": "Create policy",
        "operationId": "addPolicy",
        "parameters": [
          {
            "minLength": 1,
            "type": "string",
            "description": "An unique ID for the request",
            "name": "X-Request-Id",
            "in": "header"
          },
          {
            "description": "The policy to create",
            "name": "policy",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Policy"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The ID of the corresponding request for the response"
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Errors"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The ID of the corresponding request for the response"
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "description": "a model for all the error response coming from harbor",
      "type": "object",
      "properties": {
        "code": {
          "description": "The error code",
          "type": "string"
        },
        "message": {
          "description": "The error message",
          "type": "string"
        }
      }
    },
    "Errors": {
      "description": "The error array that describe the errors got during the handling of request",
      "type": "object",
      "properties": {
        "errors": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Error"
          }
        }
      }
    },
    "Policy": {
      "description": "The model for policy",
      "type": "object",
      "properties": {
        "id": {
          "description": "The policy id",
          "type": "integer"
        },
        "name": {
          "description": "The policy name",
          "type": "string"
        }
      }
    }
  },
  "parameters": {
    "id": {
      "minLength": 1,
      "type": "string",
      "description": "An unique ID for specific resource",
      "name": "id",
      "in": "path",
      "required": true
    },
    "requestId": {
      "minLength": 1,
      "type": "string",
      "description": "An unique ID for the request",
      "name": "X-Request-Id",
      "in": "header"
    }
  },
  "responses": {
    "200": {
      "description": "Success",
      "headers": {
        "X-Request-Id": {
          "type": "string",
          "description": "The ID of the corresponding request for the response"
        }
      }
    },
    "500": {
      "description": "Internal server error",
      "schema": {
        "$ref": "#/definitions/Errors"
      },
      "headers": {
        "X-Request-Id": {
          "type": "string",
          "description": "The ID of the corresponding request for the response"
        }
      }
    }
  },
  "securityDefinitions": {
    "basic": {
      "type": "basic"
    }
  },
  "security": [
    {
      "basic": []
    },
    {}
  ]
}`))
}
